//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionMaster
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> Stateid { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string CollectionCode { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsUserAvailable { get; set; }
        public string PriceRange { get; set; }
        public string PriceUnit { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
